#!/usr/bin/env perl

use Modern::Perl;
use Getopt::Std;

use lib qw( . );
use Twitter::Filter;

use constant INCLUDE_META => 'meta';

binmode STDOUT, ":utf8";



my $filter = Twitter::Filter->new();

# -s single item
# -n do not save (just see what'd happen)
my %opt;
getopts( 'sn', \%opt );

TWEET:
while ( 1 ) {
    my $id    = $filter->get_next_unclassified_tweet();
    my $tweet = $filter->load_tweet( $id );
    my %tweet = %$tweet;
    
    my ( $score, $tags, $buckets ) = $filter->classify_tweet( \%tweet );
    $tweet{'score'}      = $score;
    $tweet{'tags'}       = $tags;
    $tweet{'buckets'}    = $buckets;
    $tweet{'classified'} = 1;
    
    foreach my $circulator ( @{ $filter->get_circulators() } ) {
        $circulator->circulate( $filter, \%tweet );
    }
    
    print $filter->tweet_as_text( \%tweet, INCLUDE_META );
    
    $filter->update_document( $id, \%tweet )
        unless $opt{'n'};
    
    last TWEET if $opt{'s'};
}
exit;

