#!/ports/bin/perl

use Modern::Perl;

use lib qw( . );
use Twitter::Filter::Collector;

my $user = shift
    or die "Usage: direct_messages <user>";
             
my $collector = Twitter::Filter::Collector->new( 
        application => 'direct_messages',
        user        => $user
    );

$collector->queue_direct_messages();
