#!/ports/bin/perl

use Modern::Perl;

use lib qw( . );
use Twitter::Filter::Collector;

my $user = shift
    or die "Usage: home_timeline <user>";
             
my $collector = Twitter::Filter::Collector->new( 
        application => 'home_timeline',
        user        => $user
    );

$collector->queue_home_timeline();
