#!/ports/bin/perl

use Modern::Perl;

use lib qw( . );
use Twitter::Filter::Collector;

my $collector = Twitter::Filter::Collector->new( application => 'search' );
my @searches  = $collector->get_searches();

foreach my $search_term ( @searches ) {
    $collector->queue_search( $search_term );
}
