#!/usr/bin/env perl

use Modern::Perl;

use lib qw( . );
use Twitter::Filter;


my $filter  = Twitter::Filter->new();
my $twitter = $filter->get_twitter();
my $results = $twitter->saved_searches();

SEARCH:
foreach my $search ( @$results ) {
    my $term    = $search->{'query'};
    my $results = $twitter->search( $term );
    
    RESULT:
    foreach my $result ( @{ $results->{'results'} } ) {
        my $user = $result->{'from_user'};
        my $text = $result->{'text'};
        my $id   = $result->{'id'};
        
        $filter->fetch_tweet(
                $id,
                {
                    'origin'     => 'search',
                    'classified' => 0,
                }
            );
    }
}
